"""Write a clean src/patterns.rs avoiding shell-escaping issues."""
import os

lines = [
    'use crate::types::Severity;\n',
    'use regex::Regex;\n',
    'use serde::Serialize;\n',
    '\n',
    '// ── Rule ──────────────────────────────────────────────────────────────────────\n',
    '\n',
    '#[derive(Debug, Clone, Serialize)]\n',
    'pub struct Rule {\n',
    '    pub name: String,\n',
    '    pub description: String,\n',
    '    pub severity: Severity,\n',
    '    /// If true, rule only runs on .env / dotenv files.\n',
    '    pub env_only: bool,\n',
    '    #[serde(skip)]\n',
    '    pub regex: Regex,\n',
    '}\n',
    '\n',
    'impl Rule {\n',
    '    fn new(name: &str, description: &str, pattern: &str, severity: Severity) -> Self {\n',
    '        Rule {\n',
    '            name: name.into(),\n',
    '            description: description.into(),\n',
    '            severity,\n',
    '            env_only: false,\n',
    '            regex: Regex::new(pattern)\n',
    '                .unwrap_or_else(|e| panic!("bad regex for rule \'{name}\': {e}")),\n',
    '        }\n',
    '    }\n',
    '\n',
    '    fn env_rule(name: &str, description: &str, pattern: &str, severity: Severity) -> Self {\n',
    '        let mut r = Self::new(name, description, pattern, severity);\n',
    '        r.env_only = true;\n',
    '        r\n',
    '    }\n',
    '}\n',
    '\n',
    '// ── Built-in rules ────────────────────────────────────────────────────────────\n',
    '\n',
    'pub fn default_rules() -> Vec<Rule> {\n',
    '    vec![\n',
    '        // ── Private / PEM keys ───────────────────────────────────────────────\n',
    '        Rule::new("private-key-pem", "PEM-encoded private key block",\n',
    '            r"-----BEGIN (RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY( BLOCK)?-----",\n',
    '            Severity::Critical),\n',
    '        Rule::new("ssh-private-key", "OpenSSH private key header",\n',
    '            r"-----BEGIN OPENSSH PRIVATE KEY-----",\n',
    '            Severity::Critical),\n',
    '\n',
    '        // ── AWS ──────────────────────────────────────────────────────────────\n',
    '        Rule::new("aws-access-key-id", "AWS access key ID (AKIA)",\n',
    '            r"(?:^|[^A-Z0-9])(AKIA[0-9A-Z]{16})(?:[^A-Z0-9]|$)",\n',
    '            Severity::Critical),\n',
    '        Rule::new("aws-secret-access-key", "AWS secret access key (heuristic)",\n',
    # Use raw string with r#"..."# - but we need to represent this in Python carefully
    '            r#"(?i)aws[_\\-\\.]?secret[_\\-\\.]?(?:access[_\\-\\.]?)?key\\s*[:=]\\s*[\'"]?([A-Za-z0-9/+]{40})[\'"]?"#,\n',
    '            Severity::Critical),\n',
    '\n',
    '        // ── GitHub ───────────────────────────────────────────────────────────\n',
    '        Rule::new("github-pat", "GitHub personal / OAuth / app access token",\n',
    '            r"(ghp|gho|ghu|ghs|ghr|github_pat)_[A-Za-z0-9_]{20,255}",\n',
    '            Severity::Critical),\n',
    '\n',
    '        // ── Google ───────────────────────────────────────────────────────────\n',
    '        Rule::new("google-api-key", "Google API key (AIza)",\n',
    '            r"AIza[0-9A-Za-z\\-_]{35}", Severity::Critical),\n',
    '        Rule::new("google-oauth-client", "Google OAuth client ID",\n',
    '            r"[0-9]+-[0-9A-Za-z_]{32}\\.apps\\.googleusercontent\\.com",\n',
    '            Severity::High),\n',
    '\n',
    '        // ── Stripe ───────────────────────────────────────────────────────────\n',
    '        Rule::new("stripe-live-secret", "Stripe live secret key",\n',
    '            r"sk_live_[0-9a-zA-Z]{24,}", Severity::Critical),\n',
    '        Rule::new("stripe-live-public", "Stripe live publishable key",\n',
    '            r"pk_live_[0-9a-zA-Z]{24,}", Severity::High),\n',
    '        Rule::new("stripe-test-secret", "Stripe test secret key",\n',
    '            r"sk_test_[0-9a-zA-Z]{24,}", Severity::Medium),\n',
    '\n',
    '        // ── Slack ────────────────────────────────────────────────────────────\n',
    '        Rule::new("slack-token", "Slack API / bot / app token",\n',
    '            r"xox[baprs]-[0-9A-Za-z\\-]{10,}", Severity::Critical),\n',
    '        Rule::new("slack-webhook", "Slack incoming webhook URL",\n',
    '            r"https://hooks\\.slack\\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[A-Za-z0-9]+",\n',
    '            Severity::Critical),\n',
    '\n',
    '        // ── SendGrid / Twilio ─────────────────────────────────────────────────\n',
    '        Rule::new("sendgrid-api-key", "SendGrid API key",\n',
    '            r"SG\\.[A-Za-z0-9_\\-]{22}\\.[A-Za-z0-9_\\-]{43}", Severity::Critical),\n',
    '        Rule::new("twilio-api-key", "Twilio Auth token or API key SID",\n',
    '            r"SK[0-9a-fA-F]{32}", Severity::Critical),\n',
    '\n',
    '        // ── npm ──────────────────────────────────────────────────────────────\n',
    '        Rule::new("npm-access-token", "npm automation / access token",\n',
    '            r"npm_[A-Za-z0-9]{36}", Severity::Critical),\n',
    '\n',
    '        // ── JWT ──────────────────────────────────────────────────────────────\n',
    '        Rule::new("jwt-token", "JSON Web Token",\n',
    '            r"eyJ[A-Za-z0-9_\\-]{10,}\\.[A-Za-z0-9_\\-]{10,}\\.[A-Za-z0-9_\\-]{10,}",\n',
    '            Severity::High),\n',
    '\n',
    '        // ── Database connection strings ───────────────────────────────────────\n',
    '        Rule::new("db-connection-string",\n',
    '            "Database connection string with embedded credentials",\n',
    '            r"(?i)(mongodb\\+srv?|postgresql|postgres|mysql|mssql|redis|amqp)://[^:@\\s]{1,}:[^@\\s]{1,}@[^\\s]+",\n',
    '            Severity::Critical),\n',
    '\n',
    '        // ── Generic patterns ─────────────────────────────────────────────────\n',
    '        Rule::new("generic-api-key", "Generic API key assignment",\n',
    '            r#"(?i)\\bapi[_\\-]?key\\s*[:=]\\s*[\'"]?([A-Za-z0-9_\\-\\.]{20,})"#,\n',
    '            Severity::High),\n',
    '        Rule::new("generic-secret", "Generic secret assignment",\n',
    '            r#"(?i)\\b(?:app[_\\-]?|client[_\\-]?)?secret(?:[_\\-]?key)?\\s*[:=]\\s*[\'"]?([A-Za-z0-9_\\-\\./:+]{10,})"#,\n',
    '            Severity::High),\n',
    '        Rule::new("generic-password", "Hardcoded password assignment",\n',
    '            r#"(?i)\\bpassw(?:or)?d\\s*[:=]\\s*[\'"]?([^\\s\'"]{6,})"#,\n',
    '            Severity::High),\n',
    '        Rule::new("generic-token", "Generic token assignment",\n',
    '            r#"(?i)\\btoken\\s*[:=]\\s*[\'"]?([A-Za-z0-9_\\-\\.]{20,})"#,\n',
    '            Severity::High),\n',
    '        Rule::new("generic-auth-header",\n',
    '            "Authorization header with bearer/basic credential",\n',
    '            r"(?i)Authorization\\s*[:=]\\s*(?:Bearer|Basic)\\s+([A-Za-z0-9+/=_\\-\\.]{10,})",\n',
    '            Severity::High),\n',
    '        Rule::new("private-key-assignment", "Private key value in assignment",\n',
    '            r#"(?i)\\bprivate[_\\-]?key\\s*[:=]\\s*[\'"]?([A-Za-z0-9+/=_\\-]{30,})"#,\n',
    '            Severity::Critical),\n',
    '        Rule::new("heroku-api-key", "Heroku API key (UUID format)",\n',
    '            r#"(?i)heroku[^\\s]*\\s*[:=]\\s*[\'"]?[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}[\'"]?"#,\n',
    '            Severity::Critical),\n',
    '        Rule::new("basic-auth-url", "HTTP(S) URL with embedded username:password",\n',
    '            r"https?://[^:@\\s]{1,}:[^@\\s]{3,}@[^\\s]+", Severity::High),\n',
    '        Rule::new("mailgun-api-key", "Mailgun API key",\n',
    '            r#"(?i)mailgun[_\\-\\. ]?(?:api[_\\-\\. ]?)?key\\s*[:=]\\s*[\'"]?key-[0-9a-zA-Z]{32}[\'"]?"#,\n',
    '            Severity::Critical),\n',
    '\n',
    '        // ── .env – ALL uppercase VAR=VALUE .> Warning ─────────────────────────\n',
    '        Rule::env_rule("env-var-any",\n',
    '            "Environment variable assignment (all .env vars reported)",\n',
    '            r"^([A-Z][A-Z0-9_]{1,})\\s*=\\s*(.+)$", Severity::Warning),\n',
    '        // Higher severity for sensitive variable names\n',
    '        Rule::env_rule("env-var-sensitive",\n',
    '            "Sensitive environment variable name",\n',
    '            r#"(?i)^((?:[A-Za-z0-9_]*(?:secret|password|passwd|token|api[_\\-]?key|auth|private[_\\-]?key|credential|access[_\\-]?key|client[_\\-]?secret|signing[_\\-]?key)[A-Za-z0-9_]*))\\s*=\\s*([^\\s\'"].*)$"#,\n',
    '            Severity::High),\n',
    '    ]\n',
    '}\n',
    '\n',
    '/// Build a single user-supplied rule from a raw regex string.\n',
    'pub fn user_rule(index: usize, pattern: &str) -> anyhow::Result<Rule> {\n',
    '    let regex = Regex::new(pattern)\n',
    '        .map_err(|e| anyhow::anyhow!("invalid pattern \'{}\': {}", pattern, e))?;\n',
    '    Ok(Rule {\n',
    '        name: format!("custom-{}", index),\n',
    '        description: format!("User-supplied pattern: {}", pattern),\n',
    '        severity: Severity::High,\n',
    '        env_only: false,\n',
    '        regex,\n',
    '    })\n',
    '}\n',
]

out = os.path.join(os.path.dirname(__file__), '..', 'src', 'patterns.rs')
with open(out, 'w', encoding='utf-8') as f:
    f.writelines(lines)
print(f"Wrote {sum(len(l) for l in lines)} bytes to {out}")
